### PR TITLE
Implement Configuration Directory Decoupled From Base

### PR DESCRIPTION
**Pull request by NurudinImsirovic**
This PR makes minor and major changes.

Minor changes:
  - Convert all files from CRLF to LF line endings
  - Improve formatting and code styling
  - Remove empty line feeds

Major change:
  - Implement the ability to load configuration files from a single directory as opposed to sourcing from the base directory itself.
  
---

This major change allows us to decouple configurations from the base directory into their own directory.

Let's say we have 50 configurations, that's 2 files per each, so 100 files in a single directory.
Instead of that, let's have a separate directory such as `dispatcher-config`, that can either be:

- `[dispatched_directory]/dispatcher-config`
- `[home_directory]/.dispatcher-config`
- or custom set via the `DISPATCHERCFGDIR` environment variable.

In this directory we'll store the configurations for that command, which will automatically
source the file.  This behavior is ignored if the configuration file already exists in the base directory, which makes sense if you are distributing the dispatched executable alongside the configuration.

Another useful thing we could do is copy the dispatcher executable multiple times by using the configuration file names from the `dispatcher-config` directory:

```bash
C:/env/dispatcher-config>
for i in $(ls -A1); do
   CMDNAME=$(echo $i | sed -- s/\.config/\/g | sed -- s/\.exe/\/g)
   cp C:/downloads/dispatcher.exe C:/env/$CMDNAME.exe
done
```

---

Video showcase:

https://github.com/131/dispatcher/assets/102489121/df66e658-4e70-4d24-ab8e-e14603d75565

### CODE REVIEW

**Comment by oxou** [comment]
Sorry if I missed out on something, please review the code fully and make adjustments if you think there's anything to improve here.  I'm sorta in a hurry right now, cheers.

**Comment by 131** [comment]
sorry i missed this PR, i just found out about it today
ill give a look ASAP

**Comment by 131** [comment]
Since [ConfigurationManager](https://github.com/131/dispatcher/commit/84818f8ccad5120f549f83952de7f109c0269298)

We are no longer bound to a specific path (xxx.config next to xxx.exe)
So your suggestion might be relevant.
Yet : i use different node.config & node.exe (dispatched), so having a central path might generate conflict. 
(but as fallback path, it is a good idea)

**Comment by 131** [comment]
I'm okay with the intent, 'ill give a closer look to the code in the next days

**Comment by oxou** [comment]
Sure thing, no need to hurry. Take your time to inspect the PR and if you're comfortable with it then merge.  Thanks!

**Comment by oxou** [comment]
Oops, did not know deleting the fork would result in the PR getting closed.  That was unintended from my side.

**Pull request closed without merging**
